### PR TITLE
Draft: Solidify standards and switch to full typescript

### PR DESCRIPTION
**Pull request by lilyx13**
_this PR is planned to be worked on until about the middle/end of the last week of March_

## Goals of this PR
- standardize component prop patterns (there are a few variations)
- standardize component nesting patterns (links to button like links vs text links etc)
- set up a more maintainable component directory structure
- move everything to typescript
- clean up and organize pages content (establishing patterns like with the components as some of the page files have gotten a bit long)

## Outcome
Set up the codebase so it's easier to work on dynamic content, api calls, and the last bit of content. Also to make it so that contributor docs can start being drafted.

## Review Requests
- Code reviews on the patterns with using type props, naming conventions, and component organization.
- get feedback on things that could be done better or differently (this is a good time for those changes to be addressed)

### CODE REVIEW

**Comment by lilyx13** [comment]
@cdrage for prop types, would you prefer them to be declared in a global `types.ts` file or to keep them scoped with their respective components?

**Review by benoitf — COMMENTED** [review]
thanks for using typescript

I'm not sure about the `_index` files pattern.

I see sometimes
```
import Button from '@site/src/components/utilities/Button'
```

or

```
import Button from '@site/src/components/utilities/Button/_index';
```

in the latter I think it's looking odd

**Comment by lilyx13** [comment]
@benoitf the _index.tsx patterns were all just because of the migration process. [On this doc page](https://docusaurus.io/docs/creating-pages) it shows how the `_` prefix can be used to ignore routes.

**Comment by lilyx13** [comment]
So I think this is pretty much ready to rock. I want to note that there is some duplication of prop keywords that will be replaced with spread operators over the next few weeks while tweaking. Following this goal to DRY things out, I think that the move I made to use `path` as a keyword instead of `href` and `src` in types will be more of a pain because it messes with spread operator usage.

My other concern, after moving to typescript, the `react-markdown` module is having an import issue. I resolved it by lazy loading the component on import and using `Suspense` around every instance. This seems to be working but I'm not sure if it'll be the best approach longterm.

@cdrage @benoitf thank you so much for the feedback. I am going to merge this down and then follow up changes can be made to improve things as I work on the rest of the content. I just wanted to point out the above 3 concerns in particular.

**Comment by benoitf** [comment]
Hello, what is the import issue on react-markdown ?
https://stackoverflow.com/a/69748392

**Pull request merged**
