### PR TITLE
Components and Initialized Pages

### PR DESCRIPTION
**Pull request by lilyx13**
This MR tracks the building of a few utility components, hero and header section components, and card components.

It's also been used to test importing jsx components into markdown files with auto import, as well as extending the default styles.

## Definition of Done
This is merge ready when the reusable components needed across multiple pages have their base functionality tested.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@lilyx13 looks like you didn't sign your commit, and the organization requires it by default (`git commit -m "message" -s`).  You could do a `git commit --amend -s` and re-push, or I, and probably you, can just use the big merge hammer.

**Comment by lilyx13** [comment]
@TomSweeneyRedHat ah dang, I thought I added that with a local rebase yesterday. I'll amend my commits before merging by the end of the day.

**Comment by lilyx13** [comment]
I didn't know that I needed GPG keys set up and won't have time to do that today. I'll keep everything in this branch until monday.

The current content in this MR has up to the Blog post info on the index page.

**Comment by TomSweeneyRedHat** [comment]
@lilyx13 , just curious, is git requiring gpg for the signed commit?  I didn't know that  was a requirement.  Regardless, the gpg setup is a good thing to do regardless.  Happy Weekend!

**Comment by lilyx13** [comment]
@TomSweeneyRedHat hey, I'm kinda confused here. I went through and signed the commits however they're still saying unverified when I'm in vigilant mode and it's not passing the checks.

I'm not sure if the gpg is a requirement but seemed like the right way to go, however I got an error when setting that up with github, after a few tries and reviewing [this issue](https://github.com/nguyenvulong/QA/issues/25), I set it up to use ssh as that seems possible. when I check with `git log` it's now showing my commits as having been signed, but that is not seeming to update here.

This is my first time encountering this issue, would you have any docs or advice on how to proceed from here? It does have my sign-off in the commit messages now.

**Comment by TomSweeneyRedHat** [comment]
@lilyx13 computers are great when they work.  

For this particular PR, it may be wedged as you created the key after the commit.
If you want me to smash this through and merge it, just let me know, I'm happy to do that.   I just don't want to do it if you're not ready for the hammer to come down at this very moment.

Going forward,  you should setup a gpg key.  I know I had some fun hiccups when I did it prior, but I think I had stumbled on the same issue that you pointed to (https://docs.github.com/en/authentication/managing-commit-signature-verification) and that got me through it.

**Comment by lilyx13** [comment]
They certainly are hehe.

Awesome thank you for the link, I'll verify that I've got that all in good shape with a personal project over the weekend so I can go full steam next week without this hiccup.

I just pushed [this commit](https://github.com/containers/website-new/pull/8/commits/4f384286b404d82b2d25b34e8cb26cf281083c84) which fixed the error we had in my demo on thursday. I see that having pushed it, autosigning did not happen as I thought *sigh* lol. however we should be good for this PR now. 

Please use the big merge hammer 😄

**Comment by TomSweeneyRedHat** [comment]
Hammer time!

**Pull request merged**
