### PR TITLE
Adding features list

### PR DESCRIPTION
**Pull request by mairin**
- Adding header for Podman Desktop
- Adding 4 blocks of Podman Desktop features
- Adding header for Podman Command-Line

Screenshot 2023-04-30 at 16-57-01 Podman

Screenshot from 2023-04-30 16-57-37
Screenshot from 2023-04-30 16-57-34
Screenshot from 2023-04-30 16-57-30

### CODE REVIEW

**Comment by mairin** [comment]
Screenshot 2023-04-30 at 17-49-06 Podman

**Comment by mairin** [comment]
TODO I need to make better placeholder screenshots for before we have the vids available

**Comment by lilyx13** [comment]
@mairin should we wait till you get the better images b4 we merge this one?

**Comment by mairin** [comment]
@lilyx13 Fixed, should be ready to merge

**Pull request merged**
