### PR TITLE
Draft: Sprint 1: Community and Features Pages

### PR DESCRIPTION
**Pull request by lilyx13**
This PR focuses on building out the community page while enhancing components and testing them with features page content. For this PR, the Feature page will get it's static content and any components that it shares on the community or home page.

### CODE REVIEW

**Comment by benoitf** [comment]
Hello, I was wondering why jsx is used instead of tsx as typescript is part of the dependencies of the project ?

**Comment by lilyx13** [comment]
I ran into some issues with the last section of the community page (screenshot below).

This problem is related to being able to access the nested data effectively. It's possible to do it by just calling the variables one at a time, however these would get pretty long and unwieldy. It will also happen in the future with other data structures of a similar complexity.

### Solution
The solution i'm working on uses this sript
```js
const extractData = (arr) => {
  return arr.map((item) => {
    return structuredClone(item);
  });
};
which makes an immutable copy of a given object. The next step is to use this with destructured assignment to be able to pull the information out of an object and make it more sensible to access data.

[This article](https://www.freecodecamp.org/news/destructure-object-properties-using-array-map-in-react) shows the next step where data is pulled out of the array using map and assigned with destructuring.

```


Screenshot from 2023-03-17 16-07-47

## Next Steps
I don't want to hold this PR up anymore with this issue. So I'm going to focus on cleaning up the code and getting the rest of the content ready to merge first. Then this can be addressed next week.

**Comment by TomSweeneyRedHat** [comment]
FWIW, WFM

**Comment by benoitf** [comment]
> Hello, I was wondering why jsx is used instead of tsx as typescript is part of the dependencies of the project ?

Is it possible to get an answer ?

**Comment by cdrage** [comment]
> Hello, I was wondering why jsx is used instead of tsx as typescript is part of the dependencies of the project ?

I'd agree with @benoitf too that it would be beneficial for everything to be typescript for future changes to be easily implemented.

The podman desktop team uses typescript intensively and we'll be contributing to future documentation / changes to the site as well. 

It'd be an easy change as it's just changing the extension of the jsx files to tsx. So there's not much impact.

**Pull request merged**
